### ISSUE TITLE
Race condition when clearing keys allows for extracting key-vault contents as they are written

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#115]
Consider this program:

```rust
let mut doe = unsafe { DoeReg::new() };
let mut kv = unsafe { KvReg::new() };

// Start deobfuscating the UDS with IV 0
doe.regs_mut().iv().write(&[0_u32; 4]);
doe.regs_mut().ctrl().write(|w| w.dest(0).cmd(|c| c.doe_uds()));
unsafe { asm!("nop") };
// repeat the above line 204 more times
kv.regs_mut().key_ctrl().at(0).write(|w| w.clear(true));
```

It starts a deobfuscation action, then clears the key entry right before the deobfuscation is complete, before the last word is written to the key vault. The key-vault entry contents look like this after the program has executed:

![Screenshot from 2023-06-12 00-34-45](https://github.com/chipsalliance/caliptra-rtl/assets/993854/dec3af27-df0d-4602-88d7-dd710c76c82a)

As you can see from the waveform, after the clear, only the last word of the UDS is in the key-vault entry register. An attacker with code execution on the microcontroller can use this technique to extract the UDS:

1. Use the partial UDS as a key for an hmac operation, and capture the result.
2. Since the partial UDS only contains 32 bits of secret entropy, the generated hmac can be quickly brute forced to determine the last word of the UDS.
3. Hard-reset, then do the DOE operation again, but send the clear command one cycle sooner
4. Brute force the previous 32-bit word
5. Repeat steps 3-4 10 more times until the entire UDS is extracted

A similar technique can be used to extract almost any value in the key-vault as it is being written.

**Comment by bharatpillilli** [comment]
For gaining microcontroller execution, one needs to have access microcontroller when UDS is running => Caliptra is in debug mode which happens only at reset deassertion (not 'any' random time) => UDS is cleared if we are in debug mode. This essentially means you can't extract the keys if you take over the uC execution. 

Now if we say we can do that due to a FW exploitation, at that time ROM would have been done already and this flow wouldn't be possible.

**Comment by bharatpillilli** [comment]
@Nitsirks @upadhyayulakiran as a FYI of the issue

**Comment by Nitsirks** [comment]
Since the root of this issue is the ability to generate partial keys through the clear function, I think it's simple enough to restrict the clear function while an entry is being written. This way we ensure that we either clear the whole thing, or none of it.

**Comment by bharatpillilli** [comment]
> Can't a similar technique be used to extract the keys generated by the FMC?
> 
> Edit: I suppose that's not a huge issue, since the FMC identity has already been mixed into any accessible key-vault keys.

Ack to what Mike said above - but to address this question, if the issues uController execution has happened because FW is compromised, then yes....but if its to do with debug mode, then the same thing applies as the keys in key slots are debug derived anytime Caliptra is in debug mode,

**Comment by Nitsirks** [comment]
Fixing this bug triggered some internal review. We discovered the following cases where partial keys could be generated and are fixing all of them.

1) Initial find, using key clear operation to generate a partial key.
2) Use zeroize function in crypto during write to keyvault can generate a partial key.
3) Fatal error will flush keyvault with debug values while keyvault write is happening. Could possibly be timed to generate a partial key.
4) CLEAR SECRETS function in keyvault could be timed to generate a partial key.

Fixes pending for each:
1) Clear operation is held high until key write is completed. Assert error on key write to indicate that it was not successful.
2) Key vault writes will only write the dest valid bits on the last dword. This ensures that any interrupted write due to zeroize will not have valid dest to be used.
3) Fatal errors will also flush cryptos like debug unlock and scan mode switch.
4) CLEAR SECRETS will only flush the keyvault if we're in debug mode.

**Comment by Nitsirks** [comment]
Fixes are in the model now.
