### ISSUE TITLE
ETRNG data registers cannot be cleared by firmware

### ISSUE THREAD

**Issue by korran** [chipsalliance/caliptra-rtl#131]
Depending on the SoC's integration logic, the CPTRA_TRNG_DATA registers could hold their value forever, and there is no way for the UC to clear them, which may be required for FIPS zeroization.

![Screenshot from 2023-06-23 00-37-04](https://github.com/chipsalliance/caliptra-rtl/assets/993854/e2da37f9-1760-4919-8a10-af534b489fc7)

**Comment by bharatpillilli** [comment]
Caliptra access is RO on the registers - from FIPS point of view, if Caliptra has no control on the TRNG itself since eTRNG, there is nothing caliptra can do to that e-TRNG on FIPS...so this data is practically irrelevant. It is as good as "FW" FIPS dropping the data because a wrongly written/bad FW may not honor any TRNG data internal or external!

That said, if for some "hard" reasons, we need to change, its just a register permission flip.

@JohnTraverAmd to provide the requisite FIPS spec quote if we need to make changes

**Comment by JohnTraverAmd** [comment]
To be FIPS compliant, this register does need to be cleared.  It would be best if we could write to clear.

We shouldn't allow for the write to set the register value from Calitpra side since this could complicate the source of the value.  It would be best to create a mechanism to indicate that it should be cleared and have HW clear it.  This could be as simple as write anything to clear to zero and clear the valid bit.

**Comment by bharatpillilli** [comment]
@JohnTraverAmd - Ack, for process, plz bring it through for the WG for approval...would assume a 2-3 day schedule impact

**Comment by bharatpillilli** [comment]
Marking approved as the change is WIP and is required for FIPS.
RTL+Val impact wld be ~1-2 days

**Comment by upadhyayulakiran** [comment]
This change is merged to main
