### ISSUE TITLE
PCR quoting nonce is too small

### ISSUE THREAD

**Issue by jhand2** [chipsalliance/caliptra-rtl#139]
The [nonce supplied to PCR quotes](https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.sha512_reg.SHA512_GEN_PCR_HASH_NONCE) is only 32 bits. This is small enough as to make collisions fairly trivial. An attacker can feasibly collect clean attestations for a non-trivial portion of the nonce space.

I think ideally this would be a minimum of 128 bits.

**Comment by mojtaba-bisheh** [comment]
The Nonce here is only used to know the PCR quote is not stale. There is no security dependency on this nonce. The main purpose of the nonce is to allow the remote verifier to use a freshness seed.

**Comment by jhand2** [comment]
The goal of proving freshness is specifically to provide security value, there is no other purpose.

**Comment by bluegate010** [comment]
If an attacker can predict the verifier's nonce, they can provide a stale attestation which the verifier will believe is fresh.

Because this nonce is only 32 bits, an attacker can spend a not-insurmountable amount of time iterating over the nonce space, collecting measurements with each one and saving those attestations. Later, when the verifier issues a fresh attestation challenge, the attacker can observe the verifier's nonce, look up the corresponding attestation from their stash, and provide it to the verifier, thus defeating the freshness goal.

**Comment by bharatpillilli** [comment]
"If an attacker can predict the verifier's nonce, they can provide a stale attestation which the verifier will believe is fresh."
- Just to expand & understand the threat model
- Caliptra generates some NONCE and signs PCR quote on every new request
- Attack is that a 'middle' man is doing this for every possible NONCE and all possible PCR quotes (where they have control of the different FWs that Caliptra would run)
- Further, the middle man has the "hardware" access as in they were able to bypass the PAUSER and issue these requests in production mode?

**Comment by bluegate010** [comment]
We are presuming that in the normal flow, the nonce is being initially generated by the remote verifier. It is passed to Caliptra firmware via mailbox command. The nonce is not generated by Caliptra. We are also not presuming that Caliptra firmware will restrict access to this quoting API based on the PAUSER. It's not exposing a signing oracle, just a quote oracle. Firmware passes the received nonce down to the hardware, which emits a signed attestation. Firmware returns the attestation over the mailbox, and the attestation makes its way back to the remote verifier. The verifier compares the signed nonce with the one it initially generated, to check freshness.

The attack is that there's an entity that is able to challenge Caliptra with an attacker-controlled nonce. The entity could be on the same machine, or could be a network adversary. In any case, the attacker issues repeated quote requests, with different nonces, enumerating the 32-bit nonce space. The attacker saves every quote they receive.

Later, the remote verifier generates its nonce and sends it to the machine. The MITM intercepts this request and responds with a signed quote whose nonce matches the one selected by the remote verifier. The request never hits Caliptra, and the remote verifier is fooled into thinking that the response is fresh.

If the nonce were 128 bits wide, this attack would not be feasible, because it would take the attacker too long to enumerate the nonce space and use the same nonce that the remote verifier eventually selects.

**Comment by bharatpillilli** [comment]
Will fix the bug but I want to correct one thing - mailbox HW is NOT available for any random PAUSER - only valid PAUSERs set into the PUASER registers can use the mailbox...in other words, it is NOT open for all for injecting any command they want. If there is some architecture built on that assumption, it will break.

**Comment by korran** [comment]
Depending on the architecture of the security control plane, the trusted pauser may need to be proxy quote-api requests/responses from/to the outside world.

In order to prove freshness to an outside system, it is sometimes necessary to allow a not-fully-trusted system to control the nonce used for a quote.

**Comment by mojtaba-bisheh** [comment]
The bug is fixed and the nonce has been extended to 256 bits in our internal repo.

**Comment by bharatpillilli** [comment]
https://github.com/chipsalliance/caliptra-rtl/pull/149/ sync to dev-msft should fix this
