### ISSUE TITLE
Ubloaded/Undriven issue in Synthesis

### ISSUE THREAD

**Issue by Syed-mudabbir-ahsan** [chipsalliance/caliptra-rtl#314]
Hi @Nitsirks / @bharatpillilli 

We are facing some undriven and unloaded pins reported in Synthesis, Please find the attachment of the report, can you please let us know if this is expected behaviour.
[Unloaded_undriven_pins.txt](https://github.com/chipsalliance/caliptra-rtl/files/13463592/Unloaded_undriven_pins.txt)

Kindly please look into this as a priority since we have a release pending, we would like to keep the RTL clean before release to our customer.

Thanks.

**Comment by Nitsirks** [comment]
We've reviewed most of these for you already before.

Most of them are due to disabled icache and using AHB instead of axi.

A couple of them are pipeline structs where a few bits go unused in the last stage.

The last bucket are trace signals that go out to the testbench but we don't connect them anywhere else for our implementation.
