### ISSUE TITLE
NIST SP 800-90A or NIST SP 800-90B

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#336]
The Caliptra Hardware Specification in TRNG section mentions:
The PTRNG external source is a physical true random noise source. A noise source and its relation to an entropy source are defined by SP 800-90B.

Would caliptra have a problem with receiving NIST SP 800-90A data instead of NIST SP 800-90B?

**Comment by bluegate010** [comment]
Functionally, feeding data from an SP 800-90A instead of a 90B should be doable. It will be important from a FIPS narrative perspective to adhere to SP 800-90C directives regarding RBG chaining.

* If Caliptra is fed from a 90B entropy source, Caliptra's internal DRBG is classed as an RBG2. It can claim prediction resistance, and can instantiate other RBG1s.
* If Caliptra is fed from a 90A DRBG which is itself fed from a 90B entropy source, Caliptra's internal DRBG is classed as an RBG1. It cannot claim prediction resistance, and can only instantiate sub-DRBGs.
* If Caliptra is fed from a 90A DRBG which itself is fed from a different 90A DRBG, Caliptra's internal DRBG could not be certified, as SP 800-90C does not allow such a chaining arrangement.

We do not currently expose the internal DRBG to external callers, and Caliptra's internal callers do not attempt to spin up child DRBGs or sub-DRBGs. So whether Caliptra's internal DRBG is classified as an RBG1 or RBG2 is less of a concern.

If we were to begin providing entropy output to external callers, those callers - if they want to claim FIPS compliance - would need to adhere to SP 800-90C when instantiating child DRBGs using that entropy.
