### ISSUE TITLE
BootFSMBrk

### ISSUE THREAD

**Issue by RJMJJJ** [chipsalliance/caliptra-rtl#383]
Hi,

WRT https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#provisioning-idevid-during-manufacturing
it mentions in point 4:
SoC (using a GPIO pin or SoC ROM) drives BootFSMBrk (this is also used for debug cases). This can be driven at any time before cptra_rst_b is deasserted.

1] After SOC ROM asserts BootFSMBrk when is it deasserted? 
: since it is a strap it stays high and the Caliptra FSM moves to a state where it waits for CPTRA_BOOTFSM_GO to move to states carrying the boot process. So it never deasserts but control in FSM moves with CPTRA_BOOTFSM_GO.
3] As this gets asserted the Caliptra Boot FSM stops boot, but it goes through the Fuse write cycle asserting and deasserting the required signals. Please confirm.
4] So, when it stops boot what exactly the BootFSMBrk stops in Caliptra BootFSM flow?
5] How does the Tap uses it and steps through Caliptra BootFSM during debug?

**Comment by calebofearth** [comment]
1) BootFSMBrk is only observed during the boot flow as you mentioned, and the boot FSM advances past the breakpoint when SoC sets the BOOTFSM_GO register. So the only requirement on SoC is that it must set the brkpoint signal to the new desired value any time a warm reset is performed. SoC could also clear the breakpoint at any time after the boot state machine has entered the WAIT state without having any impact to the system. This is because the breakpoint value is latched internally on exit from warm reset.
3) Correct. The order of steps would be i) set brkpoint ii) deassert reset iii) set fuses iv) set fuse write done v) bootfsm_go. This is depicted in the diagram from your link above.
4) BootFSMBrk prevents the RISC-V core from being brought out of reset (and executing any ROM/firmware) until after the GO signal is set. 
5) Please refer to [JTAG/TAP Debug](https://github.com/chipsalliance/Caliptra/blob/main/doc/Caliptra.md#jtagtap-debug)

**Comment by RJMJJJ** [comment]
Thanks
