### ISSUE TITLE
running in open ssl with seed value for crypo function

### ISSUE THREAD

**Issue by harithadhulipalla** [chipsalliance/caliptra-rtl#396]
![image](https://github.com/chipsalliance/caliptra-rtl/assets/155945573/a26e972e-5e8d-4c9b-b223-d857c0e45346)

above is the code for the hmac flow for which i am trying to run a command which is mentioned below

command line:-

openssl dgst -SHA384 -mac HMAC -macopt hexkey: 0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b0b file.data

Here i want to pass a seed, please provide need a command to pass a seed into the open ssl for which it will be fix into my UVM env.

**Comment by mojtaba-bisheh** [comment]
lfsr_seed is used for SCA countermeasure embedded into HMAC design. There is no corresponding command for openssl. 
It's important to note that lfsr_seed does not change the output and only provides some randomness to avoid information leakage from hardware accelerator. Consequently, for UVM, you can safely disregard it since the expected results would remain unchanged.
