### ISSUE TITLE
Bug: Calculation Error in HMAC384 Multiblock Case

### ISSUE THREAD

**Issue by blueblue0124** [chipsalliance/caliptra-rtl#515]
Recently, I have been trying to run the test_hand_off case on FPGA and the software emulator and comparing the results from both. It seems there is a mismatch between the RT-Alias key results from the FPGA and the software emulator.

After HMAC384 completes a round of H2 calculation, the hmac internal state machine hmac_ctrl_fsm jumps to the CTRL_DONE state. Once in this state, digest_valid_new is set to 1, digest_valid_we is set to 1, and a kv_read_data_present_reset pulse signal is generated. The Key that was intended for use in the next round of calculation is cleared. However, the software emulator does not clear the Key, and this difference leads to inconsistent digest calculations, resulting in a mismatch between the RT Alias secret key generated on the FPGA and the one generated by the software emulator.

**Comment by Nitsirks** [comment]
As far as I know all of the sw test cases are passing - are you working on some change or manually comparing the results from FPGA and the emulator?

If you are changing something, it's important to note that when anything comes from or goes to the keyvault the values in the api registers of the crypto engine are flushed to prevent them from being extracted.

**Comment by LuiSzee** [comment]
We made the following modifications to the sw-emulator, so that its results are now consistent with those on the FPGA. Then, we discovered that the RTL HMAC implementation only used the first data block before storing the result to the key vault.

sw-emulator/lib/crypto/src/hmac512.rs:

    /// Update the MAC with the block
    ///
    /// # Arguments
    ///
    /// * `block` - Block to calculate MAC over
    pub fn update(&mut self, block: &[u8; BLOCK_SIZE]) {
        // hash the block
    -    self.hash1.update(block);
    +    //self.hash1.update(block);

        // Calculate the summary hash so far
        let mut sum_hash = [0u8; MAX_TAG_SIZE];

>

**Comment by LuiSzee** [comment]
This issue only occurs when generating the RT CDI. This is because the data passed to HMAC when generating the RT CDI includes 4 bytes of 1, the string "rt_alias_cdi", a null byte (0x00), and 96 bytes of TCI, totaling 113 bytes. Therefore, it requires padding to the next block. When generating other certificates using TCI of only 48 bytes, this issue does not arise.

`Crypto::hmac384_kdf(env, fmc_cdi, b"rt_alias_cdi", Some(&tci), rt_cdi)?;`
A possible workaround is to modify the "rt_alias_cdi" string in the aforementioned Calyptra FMC code to "rtaliascdi", so that the data passed to HMAC totals only 111 bytes, eliminating the need for padding to the next block.

However, we still believe that the implementation at RTL has a bug.

**Comment by Nitsirks** [comment]
We clear the block and key api registers after any operation that includes the keyvault. After the first block (init step) you would lose the key/block data but you should be able to load the key again and write the second block data and do the next step.

**Comment by bharatpillilli** [comment]
@Nitsirks  - I think this is fixed & validated; do you want to close this?
