### ISSUE TITLE
CPTRA_RESET_REASON.FW_UPD_RESET on cptra_rst_b

### ISSUE THREAD

**Issue by varuns-nvidia** [chipsalliance/caliptra-rtl#60]
https://chipsalliance.github.io/caliptra-rtl/main/internal-regs/?p=clp.soc_ifc_reg.CPTRA_RESET_REASON#FW_UPD_RESET.desc

Is this a bug?

**Comment by bharatpillilli** [comment]
Hi @varuns-nvidia  - it is not; this is differentiation FW update reset to a warm reset. If a warm reset happens, then FW update reset bit is reset to '0 because a warm reset has overridden the flow and mailbox SRAM etc. all of the logic is reset. Post warm reset, ROM goes to ICCM after whatever checks it does.

Please note that if the 'surprise' WR happens while FW Update is happening (which is **after** FW update reset has been detected by ROM, ran the authentication and now doing the copy to ICCM), then unless ROM has code to trigger 'ready_for_FW' to SOC when a surprise warm reset happens, it will be a hang state. Not sure if ROM added this capability but still mentioning it.

**Comment by varuns-nvidia** [comment]
@bharatpillilli , how does ROM/FMC/RT know that the current boot is due to a FW update reset? Would this bit persist?

**Comment by bharatpillilli** [comment]
Hi Varun - FW_UPD_RESET is set when only uC goes through reset due to writing to FW update reset bit by the uC. Since the reset domain of this bit is warm reset domain, it will reset when there is a warm reset while the warm reset bit itself gets set on a warm reset. Thereby FW will be able to distinguish between FW_update reset vs warm reset as they are mutually exclusive.

**Comment by varuns-nvidia** [comment]
Sorry, I don't follow:
* Cold Reset: RESET_REASON = 2'b0
* Warm Reset: RESET_REASON = 2'b10
* FW Update Reset: RESET_REASON = 2'b0

So how does FW distinguish Cold Reset vs FW Update Reset?

**Comment by varuns-nvidia** [comment]
Hi @bharatpillilli , could you respond to the above question?

**Comment by bharatpillilli** [comment]
Cold reset: RESET_REASON[1:0]:00
Warm Reset: RESET_REASON[1:0]: 10
FW_UPD_RESET: RESET_REASON[1:0]:01

If there is an unexpected warm reset while FW update reset is happening, RESET_REASON[1:0] will be 10

**Comment by varuns-nvidia** [comment]
>  FW_UPD_RESET: RESET_REASON[1:0]:01

What I'm not following is how this is possible when the bit itself is on cptra_rst_b

**Comment by bharatpillilli** [comment]
So FW update will make the 'core' part of caliptra to go through reset. This register/reset bit is outside of that reset domain. Implying cptra_rst_b doesnt get asserted for FW udpate reset. This is asserted only on a warm reset from SOC side

**Comment by varuns-nvidia** [comment]
Never mind I get what you're saying. Closing the ticket.
